spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/blog
  #    username: root
  #    password: password
