spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/test_db
      username: sa
      password:
