spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    open-in-view: false
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test_db
    username: sa
    password:
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        sql: debug
        type: trace